lint:
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-variantconsensus_logo_light.png
    - docs/images/nf-core-variantconsensus_logo_light.png
    - docs/images/nf-core-variantconsensus_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
  files_unchanged:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-variantconsensus_logo_light.png
    - docs/images/nf-core-variantconsensus_logo_light.png
    - docs/images/nf-core-variantconsensus_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
  multiqc_config:
    - report_comment
  nextflow_config:
    - manifest.name
    - manifest.homePage
    - validation.help.beforeText
    - validation.help.afterText
    - validation.summary.beforeText
    - validation.summary.afterText
nf_core_version: 3.3.2
repository_type: pipeline
template:
  author: "Famke Baeuerle"
  description: This pipeline takes multiple VCFs from different callers and creates
    a consensus-based VCF.
  force: false
  is_nfcore: false
  name: variantconsensus
  org: qbic-pipelines
  outdir: .
  skip_features:
    - fastqc
  version: 1.1.0dev
